#
# <https://github.com/KFERMercer/OpenWrt-CI>
#
# Copyright (C) 2019 P3TERX
#
# Copyright (C) 2020 KFERMercer
#
name: OpenWrt-CI

on:
  # schedule:
  #   - cron: 0 20 * * *
  workflow_dispatch:

jobs:
  build_openwrt:
    name: 编译OpenWrt-lean

    runs-on: ubuntu-18.04

    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - uses: actions/checkout@v2

      - name: 初始化环境
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* android*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

          df -h

      - name: 克隆代码
        run: git clone https://github.com/coolsnowwolf/lede.git

      - name: 加入额外插件
        run: |
          . ./extra.sh
                
      - name: 更新feeds
        run: |
          cd lede
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: 创建配置文件
        run: |
          cd lede
          cp -f config.txt ./lede/.config
          (echo -e \\t\\t\\t;echo;echo;echo -e \\t) | make menuconfig

      - name: 预下载
        run: |
          cd lede
          make download -j8
          find dl -size -1024c -exec rm -f {} \;

      - name: 编译
        run: |
          cd lede
          make -j$(($(nproc) + 1)) || make -j1 V=s

          
      - name: 准备打包文件
        run: |
          mkdir -p ./artifact/firmware
          cp -rf $(find ./lede/bin/targets/ -type f -name "*.img.gz") ./artifact/firmware/

          mkdir -p ./artifact/package
          cp -rf $(find ./lede/bin/packages/ -type f -name "*.ipk") ./artifact/package/
          
          mkdir -p ./artifact/buildinfo
          cp -rf $(find ./bin/targets/ -type f -name "*.buildinfo" -o -name "*.manifest") ./artifact/buildinfo/
          cp -f ./lede/.config ./artifact/buildinfo/config.txt

      - name: 修正SD卡分区表
        run: . ./fixPT.sh
          
      - name: Deliver buildinfo
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_buildinfo
          path: ./artifact/buildinfo/

      - name: Deliver package
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_package
          path: ./artifact/package/

      - name: Deliver firmware
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_firmware
          path: ./bin/targets/

      - name: Upload release asset
        if: github.event == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.YOURTOKEN }}
          file: ./artifact/firmware/*
          tag: ${{ github.ref }}
          file_glob: true
